# Generated by Django 4.2.2 on 2023-06-18 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choices_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date published',
            new_name='pub_date',
        ),
    ]
